// <auto-generated />
using BlazorECommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "is an epic high-fantasy novel[a] by English author and scholar J. R. R. Tolkien. Set in Middle-earth, \r\n                                   intended to be Earth at some distant time in the past, the story began as a sequel to Tolkien's 1937 \r\n                                   children's book The Hobbit",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e9/First_Single_Volume_Edition_of_The_Lord_of_the_Rings.gif",
                            Price = 19.95m,
                            Title = "Lord of the rings"
                        },
                        new
                        {
                            Id = 2,
                            Description = " is a science fiction novel by American writer Isaac Asimov. It is the first published in his Foundation Trilogy\r\n                                         (later expanded into the Foundation series). Foundation is a cycle of five interrelated short stories",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/25/Foundation_gnome.jpg",
                            Price = 22.50m,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "is a 1953 dystopian novel by American writer Ray Bradbury. Often regarded as one of his best works,\r\n                                        the novel presents a future American society where books are outlawed and 'firemen' burn any that are found.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/db/Fahrenheit_451_1st_ed_cover.jpg",
                            Price = 49.15m,
                            Title = "Fahrenheit 451"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
